# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0002_auto_20180729_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydata',
            name='satisfaction_score',
            field=models.IntegerField(),
        ),
    ]
