# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0003_auto_20180731_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydata',
            name='image',
            field=models.ImageField(blank=True, upload_to='pro_img'),
        ),
    ]
