# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import myop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0004_journeydata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydata',
            name='image',
            field=models.ImageField(blank=True, upload_to=myop_app.models.JourneyData._upload_path),
        ),
    ]
