# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0005_auto_20180809_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydata',
            name='is_OnlinePreopElig',
            field=models.BooleanField(default=False),
        ),
    ]
