# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import myop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0007_auto_20180811_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydata',
            name='msg_FromPatient',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='msg_ToPatient',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='msg_image',
            field=models.ImageField(blank=True, upload_to=myop_app.models.JourneyData._upload_path_msg),
        ),
        migrations.AlterField(
            model_name='journeydata',
            name='pod15_satisfaction_score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='journeydata',
            name='pod1_satisfaction_score',
            field=models.IntegerField(default=-1),
        ),
    ]
