# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0008_auto_20180811_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydata',
            name='Alert_msg',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='is_Alert',
            field=models.BooleanField(default=False),
        ),
    ]
