# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0009_auto_20180812_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydata',
            name='days_to_op',
            field=models.IntegerField(default=-1),
        ),
    ]
