# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0010_journeydata_days_to_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydata',
            name='days_to_op',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
