# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0012_auto_20180812_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeydata',
            old_name='Alert_msg',
            new_name='Alert_msg_fromPt',
        ),
        migrations.RenameField(
            model_name='journeydata',
            old_name='is_Alert',
            new_name='is_Alert_fromPt',
        ),
        migrations.AddField(
            model_name='journeydata',
            name='Alert_msg_toPt',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='is_Alert_toPt',
            field=models.BooleanField(default=False),
        ),
    ]
