# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0014_auto_20180812_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeydata',
            old_name='Alert_msg_fromPt',
            new_name='Alert_msg_toHosp',
        ),
        migrations.RenameField(
            model_name='journeydata',
            old_name='is_Alert_fromPt',
            new_name='is_Alert_toHosp',
        ),
    ]
