# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0015_auto_20180812_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journeydata',
            old_name='Alert_msg_toPt',
            new_name='AlertMsgFromServToPt',
        ),
        migrations.RenameField(
            model_name='journeydata',
            old_name='is_Alert_toPt',
            new_name='IsAlertFromServToPt',
        ),
        migrations.AddField(
            model_name='journeydata',
            name='AboutAnesLinks',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='AboutOpSurgeryLinks',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='AboutPhysioLinks',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='AboutWoundCareLinks',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='MsgFromPtToServ',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='MsgFromServToPt',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='UnixTimeOfLastSync',
            field=models.BigIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='is_PostOpArf',
            field=models.BooleanField(default=False),
        ),
    ]
