# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0016_auto_20180818_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydata',
            name='AlertMsgFromPtToServ',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='IsAlertFromPtToServ',
            field=models.BooleanField(default=False),
        ),
    ]
