# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0017_auto_20180819_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydata',
            name='isOnMeds',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='isSick',
            field=models.BooleanField(default=False),
        ),
    ]
