# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0018_auto_20180820_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydata',
            name='journey_point',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='journeydata',
            name='op_date',
            field=models.DateField(blank=True),
        ),
    ]
