# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0020_auto_20180820_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydata',
            name='op_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
