# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0022_journeydata_is_onlinepreopelig'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydata',
            name='patient_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
