# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0026_auto_20180901_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydata',
            name='UnixTimeOfLastSync',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
