# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0027_auto_20180905_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydata',
            name='op_name',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=50),
        ),
    ]
