# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0028_auto_20180913_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydata',
            name='journey_point',
            field=models.CharField(blank=True, choices=[('preop', 'preop'), ('preop_GotoClinic', 'preop_GotoClinic'), ('preopMedPhoto', 'preopMedPhoto'), ('Reminder1', 'Reminder1'), ('Reminder2', 'Reminder2'), ('UnkwnOpStatus', 'UnkwnOpStatus'), ('POD1', 'POD1'), ('POD3', 'POD3'), ('POD5', 'POD5'), ('POD10', 'POD10'), ('POD15', 'POD15'), ('SuperSync', 'SuperSync'), ('DEAD', 'DEAD')], default='preop', max_length=100),
        ),
        migrations.AlterField(
            model_name='journeydata',
            name='op_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
