# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import myop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0030_auto_20180923_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeydata',
            name='AnesthVideoLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='FCM',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='PhysioVideoLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='PreopInstructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='SurgeryVideoLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='journeydata',
            name='WoundCareVideoLink',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='journeydata',
            name='AboutAnesLinks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydata',
            name='AboutOpSurgeryLinks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydata',
            name='AboutPhysioLinks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydata',
            name='AboutWoundCareLinks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journeydata',
            name='image',
            field=models.ImageField(blank=True, upload_to=myop_app.models.JourneyData._upload_path),
        ),
    ]
