# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import myop_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('myop_app', '0032_auto_20180923_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeydata',
            name='image',
            field=models.ImageField(blank=True, upload_to=myop_app.models.JourneyData._upload_path),
        ),
    ]
